### ISSUE TITLE
DexIndexOverflowException 65536

### ISSUE THREAD

**Issue by hesling** [google/iosched#144]
hi, i just check out the latest code and run le android app module in le AS1.2, 
then i get le com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536 exception 
what's wrong with it?

**Comment by PaulRashidi** [comment]
I'm looking at this now.

**Comment by hesling** [comment]
hi, sorry but have you resolved it yet?

**Comment by sulimanQasim** [comment]
hello can you send me a link ?


2015-07-13 6:19 GMT+03:00 hesling <notifications@github.com>:

**Comment by hesling** [comment]
link? what kind of link?

**Comment by eneim** [comment]
This Exception normally related to "TOO BIG Dex" problem I suppose. Did you check the MultiDex enable on your project? If not, please refer this to try

[https://developer.android.com/tools/building/multidex.html](https://developer.android.com/tools/building/multidex.html)

**Comment by hesling** [comment]
oh, thx, i will have a try

**Comment by PaulRashidi** [comment]
Sorry, I have been traveling. Multidexing isn't the correct solution for an app of this size. I'm not able to reproduce your issue issue, but if you enable minification in the android build.gradle file for the debug build variant it should get around the issue but build slower. Alternatively, you can upgrade the 2014 source (the version you're currently seeing) to use the newest Google Play services client lib (7.5) then you can utilize the dependencies like this in build.gradle which will include far less methods in your dex. That requires a little bit of modification of other code since a few things in the library have changed between 6.1 and 7.5 (soon to be 7.8).

    def googlePlayServicesVersion = "6.5.87"
    compile "com.google.android.gms:play-services-wearable:${googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-drive:${googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-plus:${googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-analytics:${googlePlayServicesVersion}"
    compile "com.google.android.gms:play-services-maps:${googlePlayServicesVersion}"

**Comment by hesling** [comment]
Many thanks for your replying.

**Comment by PaulRashidi** [comment]
Did that resolve the issue for you? The 2015 source (when released) already uses the split client libs and doesn't us the REST-based client libs so dex method/field count isn't an issue.

**Comment by hesling** [comment]
Yes, thx, it did! BTW, when exactly will the 2015 source be released?
