### ISSUE TITLE
Question: Why is the Data Bootstrapping implemented as a service?

### ISSUE THREAD

**Issue by Bradleycorn** [google/iosched#178]
I'm curious, why the loading of the bootstrap data is implemented as a service? 

``` java
    public static void startDataBootstrapIfNecessary(Context context) {
        if (!SettingsUtils.isDataBootstrapDone(context)) {
            LOGW(TAG, "One-time data bootstrap not done yet. Doing now.");
            context.startService(new Intent(context, DataBootstrapService.class));
        }
    }
```

The SyncAdapter checks to see if the bootstrap data has been loaded and if not, it kicks off the service (by calling the method above), and then returns. 

``` java
   public boolean performSync(@Nullable SyncResult syncResult, Account account, Bundle extras) {
        boolean dataChanged = false;

        if (!SettingsUtils.isDataBootstrapDone(mContext)) {
            LOGD(TAG, "Sync aborting (data bootstrap not done yet)");
            // Start the bootstrap process so that the next time sync is called,
            // it is already bootstrapped.
            DataBootstrapService.startDataBootstrapIfNecessary(mContext);
            return false;
        }

       ...
}
```

I'm just wondering if there is a compelling reason for implementing a service specifically for this task (as opposed to just loading the bootstrap data "inline" in the SyncAdapter), or if "that's just the way we did it".

**Comment by eneim** [comment]
I think the idea is to ask a Background task to do the heavy job (asking for data from cloud), so using an Intent Service here is a good way to go. Didn't check the code for detail, but it's a general good practice IMO.

**Comment by Bradleycorn** [comment]
I agree, but the bootstrap data is not pulled from the cloud. It's included as a json file in the app package when the app is installed. The Databootstrap service just loads that parses that included json file and uses it for initial database population.

**Comment by eneim** [comment]
I got your point. You can absolutely move it to a main thread process. 

But for more flexible usage, for example loading data from cloud in the future, or custom data loading, putting them to an Intent Service can save a lot of resources. 

If you implement your own App from iosched code base, I suppose it will be helpful. Further more, save some milliseconds from parsing that json, and spend it for UI thread is not that bad. And since that Intent Service will end in a blink (suppose that current json is relatively small), you would not need to worry about any further resource issue.

Though using Intent Service for small task may be overkill, I agree with the way to move all loading and parsing stuff into background tasks, and leave the Main thread to do UI task only.

**Comment by passionli** [comment]
intentService is  a Service component wrapped a thread pool to do serialized jobs. Using a Service to avoid killed by the system rather than just using a thread.

**Comment by JoseAlcerreca** [comment]
Obsolete
