### ISSUE TITLE
Create presenter inside or outside fragment?

### ISSUE THREAD

**Issue by juanmeanwhile** [google/iosched#239]
Hi, 

Taking a look to FeedActivity the presenter is created there and assigned to the fragment, but in SessionDetailsActivity it is created inside the view (SessionDetailFragment). Any reason to do that in two different ways?

**Comment by elmargomez** [comment]
Before I explain let me show you first the the `PresenterImpl` class.
```

    public PresenterImpl(M model, UpdatableView<M, Q, UA> view, UA[] validUserActions, Q[] initialQueries) 
    /**
     * Use this constructor if this Presenter controls more than one view.
     */
    public PresenterImpl(M model, @Nullable UpdatableView<M, Q, UA>[] views, UA[] validUserActions,Q[] initialQueries) 
```
If you notice those constructors we can see a `single UpdatableView` and an `array of UpdatableView`. The Presenter can actually handle multiple views and centralize the presenter code in 1 class however you/we can only pass a single model. What does it mean? So if multiple views (e.g. Fragment) shares the same Model logic it is overkill to put Presenter in the Fragment itself (e.g. `ViewPager` that contains multiple similar Fragments) but if the Model is only exclusive for a single view then placing the Presenter and Model inside the view (e.g. like `SessionDetailFragment`) itself is a lot cleaner. 

Conclusion: If your Model will be used in Multiple views like Fragment then you need to put your Presenter and Model in the Activity otherwise place it in the Fragment.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
