### ISSUE TITLE
This app won't run unless you update Google Play services

### ISSUE THREAD

**Issue by VihaanVerma89** [google/iosched#37]
![device-2014-08-16-031551](https://cloud.githubusercontent.com/assets/4493362/3939354/09c0268a-24c6-11e4-922d-510387f87eef.png)
![device-2014-08-16-031610](https://cloud.githubusercontent.com/assets/4493362/3939355/09c2d998-24c6-11e4-92eb-da1600e47a75.png)

When trying to run the app I m prompted to update the google play service , upon clicking on update I don't see any update option. The same thing happen on my Nexus4 which is not he case when I install the Google I/O app directly from play store.

How can this be fixed ?

**Comment by DPARJUNAHI** [comment]
This type of message is always coming in my Moto G(First Generation) after updating it to android 5.0.2 and after clicking it, it  go to Google Play Services (Google Ink) with Uninstall and Open option. After this I can not understand that how to fix this problem, because there is no other option on the screen to update an application. So that I request you to kindly guide me.

**Comment by PaulRashidi** [comment]
There was a problem when this bug was first posted related to the client library that has been fixed.

The same error message presents itself when the following occurs and isn't typically considered a bug (but we are working to make this experience better for users and devs):
When you flash a device or receive an OTA the embedded Google Play services APK may have been replaced with an older version of the services APK. The client library that is compiled into the app is a newer version that needs to talk to the newer services APK. Google Play services will update itself from Google Play Store in the background and this error will eventually go away. In an OTA or new device setup where you restored your device from an online backup the Google Play services APK can get stuck in the back of a large queue. Rebooting your phone will typically refresh the Google Play Store app update list if you have nothing listed to download.

**Comment by zubairkharoti** [comment]
![screenshot_2015-03-01-18-39-47](https://cloud.githubusercontent.com/assets/11263637/6434695/81fe8610-c042-11e4-91bc-94e07fb48edf.png)
Can someone please help I have a next book 7.85 tablet and the the same thing happens

**Comment by zubairkharoti** [comment]
Then this happens when I click on it
![screenshot_2015-03-01-18-39-57](https://cloud.githubusercontent.com/assets/11263637/6434698/9a5c43fa-c042-11e4-8593-37833000c459.png)

**Comment by zubairkharoti** [comment]
I have tried everything for about 3-4 months and still nothing my tablet used to be rooted and then this happened when I unroot it. When I try root again with the same method using kingo root it says waiting for device then my tablet turns off. When I turn it on it then it turns back off. I have tried clearing cache but idk how to remove my account from the tablet. When I go to gmail it says google services needs to be updated to work but when I click on it, it says google play services is not compatible with your device and it used to be.
![screenshot_2015-03-01-18-47-10](https://cloud.githubusercontent.com/assets/11263637/6434739/8998a094-c043-11e4-89c8-8408f1b2d8e1.png)

![screenshot_2015-03-01-18-47-56](https://cloud.githubusercontent.com/assets/11263637/6434742/911ac1ee-c043-11e4-8758-6e37bdce481c.png)

**Comment by zubairkharoti** [comment]
Please someone help I beg I can't take this anymore and I'm only 12 yrs old. I messed with the build.prop but no I can't edit it because I can't root please I beg a lot

**Comment by DPARJUNAHI** [comment]
I had also faced this type of notification on my Moto G and now I overcome
on this. First you please go to setting then click on apps after this click
on Google Play Services. Funally you should click uninstall updates
of Google Play Services. After doing it, this type of notification will not
appeare in future.

On Mon, Mar 2, 2015 at 8:21 AM, zubairkharoti <notifications@github.com>
wrote:

> Please someone help I beg I can't take this anymore and I'm only 12 yrs
> old. I messed with the build.prop but no I can't edit it because I can't
> root please I beg a lot
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/google/iosched/issues/37#issuecomment-76651385>.
>



--

**Comment by zubairkharoti** [comment]
Yeah I have tried that but didn't work I can't get any app

**Comment by PaulRashidi** [comment]
Hi @zubairkharoti, This issue is for the Google I/O Scheduling app. It does have advice for developers of other apps that run into the same issue, but debugging a rooted device's issue is sort of out of scope. Between rooting, unrooting, not being able to root again, and modifying build.prop I think you might have gotten to a bad enough state to warrant starting back at stock. I suggest you use the support forum for the tool you used to root. Thanks, Paul

**Comment by 00001jay** [comment]
I know this is old but i encounted this error due to me turning off androids permissions in security, users, As soon as i allowed android permission it fixed the problem.

**Comment by PaulRashidi** [comment]
The currently public version of the app doesn't target Android M so you would have received a warning when you disabled the permissions indicating the app may not work correctly. The app uses Google Play services and if you do things to your device that result the device not receiving updates to Google Play services this issue will present itself.

**Comment by 00001jay** [comment]
yep, finally rooted my tab and couldnt figure out why it wouldnt update, I caused no end of dramas turning that permission off. Ended up factory resetting the thing

**Comment by parvezkarim** [comment]
The same problem is happen to me from 2 days..please someone help what to do now..I have HTC  e9 plus

**Comment by DevenCris** [comment]
This happened to me when I installed a new CM ROM. Just go to Apk download site and get the latest version of Google Play Services to install. If you check I'm sure you'll find the current version you run is probably a few versions older. Mine fixed it self btw but I was able to spot the version difference before it did.

**Comment by nisfuf** [comment]
i've the same problem with xiaomi mi4c after i reset it to the reset factory, but i haven't installed the google app.

anybody can fix my problem?

**Comment by mathiastck** [comment]
could try https://github.com/opengapps/opengapps/wiki/FAQ
