### ISSUE TITLE
Static third party libraries should be replaced by gradle dependencies

### ISSUE THREAD

**Issue by anirudh24seven** [google/iosched#54]
Static libraries (the ones under iosched/third_party) should be removed and gradle dependencies should be used instead (wherever possible, e.g. glide).

**Comment by PaulRashidi** [comment]
Glide is no longer a third_party directory dependency in 2015 source. We use this directory when we need to patch something because a fix isn't yet released to maven or the dependency simply isn't available via maven repos.

We usually have documentation about this in the subdirectories' README.google file.
