### ISSUE TITLE
Why getFragmentManager and not getSupportFragmentManager?

### ISSUE THREAD

**Issue by kjeremy** [google/iosched#84]
I know this isn't really an issue it's more of a question but why does iosched use the fragment manager and not the support version?  If you use ActionBarActivity isn't best practices to use the support version?

**Comment by anuragdake** [comment]
We generally use getSupportFragmentManager(), if we want our app to be compatible on devices below API 14.
If your app is build for API >=14, then we can directly use getFragmentManager().
In this application, minSdkVersion is set to 14, thats why getFragmentManager() is used instead of getSupportFragmentManager().

**Comment by JoseAlcerreca** [comment]
Obsolete
